import type {
  BeaconData,
  CompaniesData,
  ContentData,
  SettingsData,
} from "./types";

export const MOCK_DATA: BeaconData = {
  newMatches: [
    { id: "j1", title: "Staff Product Engineer", company: "Anthropic",  score: 94, comp: "$260–320k", loc: "SF · Hybrid",    seniority: "Staff",  stack: ["Python", "TypeScript", "Inference"], posted: "2h", referral: true  },
    { id: "j2", title: "Founding Design Eng",    company: "Browser Co", score: 91, comp: "$220–280k", loc: "Remote · US",    seniority: "Senior", stack: ["Swift", "React", "WebKit"],         posted: "4h", referral: false },
    { id: "j3", title: "ML Platform Engineer",   company: "Harvey",     score: 88, comp: "$240–300k", loc: "NYC · Onsite",   seniority: "Senior", stack: ["Ray", "Kubernetes", "Python"],       posted: "6h", referral: true  },
    { id: "j4", title: "Product Engineer",       company: "Cursor",     score: 86, comp: "$200–260k", loc: "SF · Hybrid",    seniority: "Senior", stack: ["TypeScript", "Rust", "LSP"],         posted: "9h", referral: false },
    { id: "j5", title: "Applied AI Engineer",    company: "Perplexity", score: 82, comp: "$230–290k", loc: "SF · Hybrid",    seniority: "Senior", stack: ["Python", "RAG", "Evals"],            posted: "14h",referral: false },
    { id: "j6", title: "Design Engineer",        company: "Linear",     score: 79, comp: "$210–270k", loc: "Remote · Global",seniority: "Senior", stack: ["React", "TypeScript", "GraphQL"],    posted: "1d", referral: true  },
  ],
  pipeline: [
    { id: "a1", company: "Vercel",    role: "Staff FE",       stage: "Screen",  since: 3,  owner: "me", next: "Recruiter call Thu", ghost: false },
    { id: "a2", company: "Ramp",      role: "Sr Product Eng", stage: "Onsite",  since: 1,  owner: "me", next: "Onsite loop Apr 28", ghost: false },
    { id: "a3", company: "Notion AI", role: "Applied AI",     stage: "Applied", since: 11, owner: "me", next: "Follow up today",   ghost: true  },
    { id: "a4", company: "Replit",    role: "Design Eng",     stage: "Applied", since: 6,  owner: "me", next: "Awaiting",           ghost: false },
  ],
  interviews: [
    { company: "Vercel", role: "Staff FE",       when: "Thu · 2:00p",  kind: "Recruiter",  who: "L. Park", prep: 60 },
    { company: "Ramp",   role: "Sr Product Eng", when: "Mon · 10:00a", kind: "Onsite",     who: "4 loops", prep: 30 },
    { company: "Harvey", role: "ML Platform",    when: "Apr 29",       kind: "Hiring Mgr", who: "S. Chen", prep: 10 },
  ],
  news: [
    { company: "Anthropic", text: "Released Claude 4.5 Haiku · AI model", when: "3h", kind: "product" },
    { company: "Cursor",    text: "Raised $900M Series C at $9.5B",        when: "1d", kind: "funding" },
    { company: "Harvey",    text: "Hired Jane Doe as VP Eng",               when: "2d", kind: "hire"    },
    { company: "Replit",    text: "Launched Agent v3 · new autonomy tier",  when: "3d", kind: "product" },
  ],
  sync: [
    { t: "14:02", cmd: "beacon pull --watchlist",   msg: "94 companies scanned · 12 new matches", ok: true  },
    { t: "14:02", cmd: "beacon enrich anthropic",   msg: "Funding + headcount refreshed",         ok: true  },
    { t: "13:58", cmd: "beacon rank",                msg: "6 jobs moved above threshold (85+)",    ok: true  },
    { t: "09:14", cmd: "beacon pull linkedin",       msg: "rate-limited · retrying in 20m",        ok: false },
    { t: "08:00", cmd: "beacon resume check",        msg: "stale 11d · tailored variant for Ramp", ok: true  },
  ],
  stats: { applied: 14, responses: 6, interviews: 3, offers: 0, responseRate: 0.43 },
  follow: [
    { who: "Notion AI",      role: "Applied AI", days: 11, tone: "bad",    action: "Follow up · 11d since apply" },
    { who: "Linear · B. Ho", role: "Warm intro", days: 6,  tone: "warn",   action: "Reply to intro email" },
    { who: "Harvey",         role: "Take-home sent", days: 2, tone: "default", action: "Submit by Fri" },
  ],
};

export const MOCK_COMPANIES: CompaniesData = {
  companies: [
    {
      id: 1,
      name: "Anthropic",
      domain: "anthropic.com",
      tier: 1,
      score: 9.4,
      remotePolicy: "hybrid",
      hqLocation: "San Francisco, CA",
      industry: "AI Research",
      description: "AI safety company building reliable, interpretable AI systems.",
      careersUrl: "https://www.anthropic.com/careers",
      careersPlatform: "greenhouse",
      lastResearchedAt: "2026-04-26T14:02:00Z",
      lastResearchedAge: "3d",
      toolsList: [
        { name: "Claude Code", adoption: "required", evidenceUrl: null },
        { name: "Cursor", adoption: "encouraged", evidenceUrl: null },
      ],
      openJobs: 14,
      signals: [
        {
          id: 11,
          type: "leadership_statement",
          title: "Dario on Claude-as-coworker",
          excerpt: "Engineers ship 2-3x faster with Claude in the loop, and quality goes up.",
          sourceUrl: "https://example.com/dario",
          sourceName: "Lex Fridman",
          strength: 5,
          dateObserved: "2026-03-12",
        },
        {
          id: 12,
          type: "engineering_blog",
          title: "How we use Claude internally",
          excerpt: "Every PR is reviewed by Claude before a human sees it.",
          sourceUrl: "https://anthropic.com/news",
          sourceName: "Anthropic blog",
          strength: 5,
          dateObserved: "2026-02-08",
        },
      ],
      leadership: [
        {
          id: 21,
          leader: "Dario Amodei",
          title: "CEO",
          signalType: "interview",
          content: "Code generation will fundamentally restructure software teams in the next 18 months.",
          sourceUrl: null,
          dateObserved: "2026-03-12",
          impactLevel: "company-wide",
        },
      ],
      breakdown: {
        leadership: 9.5,
        toolAdoption: 9.8,
        culture: 9.4,
        evidenceDepth: 9.0,
        recency: 9.2,
        composite: 9.4,
        lastComputedAt: "2026-04-28T10:00:00Z",
      },
    },
    {
      id: 2,
      name: "Cursor",
      domain: "cursor.sh",
      tier: 1,
      score: 9.1,
      remotePolicy: "hybrid",
      hqLocation: "San Francisco, CA",
      industry: "Developer Tools",
      description: "AI-native code editor built on top of VS Code.",
      careersUrl: "https://cursor.sh/careers",
      careersPlatform: "ashby",
      lastResearchedAt: "2026-04-22T09:30:00Z",
      lastResearchedAge: "7d",
      toolsList: [
        { name: "Cursor", adoption: "required", evidenceUrl: null },
      ],
      openJobs: 8,
      signals: [
        {
          id: 13,
          type: "press_coverage",
          title: "Series C $900M at $9.5B",
          excerpt: "Cursor raises $900M at a $9.5B valuation to accelerate AI-native IDE development.",
          sourceUrl: "https://example.com/news",
          sourceName: "TechCrunch",
          strength: 4,
          dateObserved: "2026-04-15",
        },
      ],
      leadership: [],
      breakdown: {
        leadership: 9.0,
        toolAdoption: 9.5,
        culture: 9.0,
        evidenceDepth: 8.8,
        recency: 9.4,
        composite: 9.1,
        lastComputedAt: "2026-04-28T10:00:00Z",
      },
    },
    {
      id: 3,
      name: "Vercel",
      domain: "vercel.com",
      tier: 1,
      score: 8.8,
      remotePolicy: "remote-first",
      hqLocation: "San Francisco, CA",
      industry: "Cloud Platform",
      description: "Frontend cloud platform for the AI era.",
      careersUrl: "https://vercel.com/careers",
      careersPlatform: "greenhouse",
      lastResearchedAt: "2026-04-19T15:12:00Z",
      lastResearchedAge: "10d",
      toolsList: [
        { name: "v0", adoption: "encouraged", evidenceUrl: null },
        { name: "Cursor", adoption: "encouraged", evidenceUrl: null },
      ],
      openJobs: 11,
      signals: [],
      leadership: [],
      breakdown: {
        leadership: 8.5,
        toolAdoption: 9.0,
        culture: 8.8,
        evidenceDepth: 8.6,
        recency: 8.9,
        composite: 8.8,
        lastComputedAt: "2026-04-28T10:00:00Z",
      },
    },
    {
      id: 4,
      name: "Harvey",
      domain: "harvey.ai",
      tier: 1,
      score: 8.6,
      remotePolicy: "hybrid",
      hqLocation: "New York, NY",
      industry: "Legal AI",
      description: "Generative AI built for law firms.",
      careersUrl: "https://harvey.ai/careers",
      careersPlatform: "lever",
      lastResearchedAt: "2026-04-15T10:00:00Z",
      lastResearchedAge: "14d",
      toolsList: [
        { name: "Claude Code", adoption: "encouraged", evidenceUrl: null },
      ],
      openJobs: 6,
      signals: [],
      leadership: [],
      breakdown: {
        leadership: 8.4,
        toolAdoption: 8.5,
        culture: 8.6,
        evidenceDepth: 8.4,
        recency: 8.8,
        composite: 8.6,
        lastComputedAt: "2026-04-28T10:00:00Z",
      },
    },
    {
      id: 5,
      name: "Browser Co",
      domain: "thebrowser.company",
      tier: 2,
      score: 7.8,
      remotePolicy: "remote-first",
      hqLocation: "New York, NY",
      industry: "Consumer AI",
      description: "Building Arc and Dia, browsers for the AI era.",
      careersUrl: "https://thebrowser.company/careers",
      careersPlatform: "ashby",
      lastResearchedAt: "2026-04-10T10:00:00Z",
      lastResearchedAge: "19d",
      toolsList: [
        { name: "Cursor", adoption: "encouraged", evidenceUrl: null },
      ],
      openJobs: 4,
      signals: [],
      leadership: [],
      breakdown: {
        leadership: 7.5,
        toolAdoption: 8.0,
        culture: 7.8,
        evidenceDepth: 7.6,
        recency: 7.9,
        composite: 7.8,
        lastComputedAt: "2026-04-28T10:00:00Z",
      },
    },
    {
      id: 6,
      name: "Linear",
      domain: "linear.app",
      tier: 2,
      score: 7.4,
      remotePolicy: "remote-first",
      hqLocation: "Distributed",
      industry: "Project Management",
      description: "Issue tracking tool for software teams.",
      careersUrl: "https://linear.app/careers",
      careersPlatform: "greenhouse",
      lastResearchedAt: "2026-04-04T10:00:00Z",
      lastResearchedAge: "25d",
      toolsList: [
        { name: "Claude Code", adoption: "allowed", evidenceUrl: null },
      ],
      openJobs: 3,
      signals: [],
      leadership: [],
      breakdown: {
        leadership: 7.0,
        toolAdoption: 7.6,
        culture: 7.4,
        evidenceDepth: 7.2,
        recency: 7.5,
        composite: 7.4,
        lastComputedAt: "2026-04-28T10:00:00Z",
      },
    },
    {
      id: 7,
      name: "Replit",
      domain: "replit.com",
      tier: 2,
      score: 7.2,
      remotePolicy: "remote-first",
      hqLocation: "Foster City, CA",
      industry: "Developer Tools",
      description: "Browser-based IDE with AI-native agent.",
      careersUrl: "https://replit.com/careers",
      careersPlatform: "ashby",
      lastResearchedAt: "2026-04-12T10:00:00Z",
      lastResearchedAge: "17d",
      toolsList: [
        { name: "Replit Agent", adoption: "required", evidenceUrl: null },
      ],
      openJobs: 5,
      signals: [],
      leadership: [],
      breakdown: {
        leadership: 7.0,
        toolAdoption: 7.4,
        culture: 7.2,
        evidenceDepth: 7.0,
        recency: 7.3,
        composite: 7.2,
        lastComputedAt: "2026-04-28T10:00:00Z",
      },
    },
    {
      id: 8,
      name: "Perplexity",
      domain: "perplexity.ai",
      tier: 1,
      score: 8.2,
      remotePolicy: "hybrid",
      hqLocation: "San Francisco, CA",
      industry: "AI Search",
      description: "AI-powered answer engine.",
      careersUrl: "https://perplexity.ai/careers",
      careersPlatform: "ashby",
      lastResearchedAt: "2026-04-21T10:00:00Z",
      lastResearchedAge: "8d",
      toolsList: [
        { name: "Cursor", adoption: "encouraged", evidenceUrl: null },
      ],
      openJobs: 9,
      signals: [],
      leadership: [],
      breakdown: {
        leadership: 8.0,
        toolAdoption: 8.4,
        culture: 8.2,
        evidenceDepth: 8.0,
        recency: 8.3,
        composite: 8.2,
        lastComputedAt: "2026-04-28T10:00:00Z",
      },
    },
  ],
  totalTools: ["Claude Code", "Cursor", "Replit Agent", "v0"],
};

export const MOCK_CONTENT: ContentData = {
  drafts: [
    {
      id: 1,
      contentType: "linkedin_post",
      platform: "LinkedIn",
      title: "Why I switched from REST to GraphQL Federation",
      status: "draft",
      publishedUrl: null,
      publishedAt: null,
      updatedAt: "2026-04-25T10:00:00Z",
      daysSinceUpdate: 4,
      preview: "After three years of patching REST endpoints, the migration paid for itself in week one…",
    },
    {
      id: 2,
      contentType: "blog_post",
      platform: "personal-site",
      title: "Building a beacon: 38 companies, one Claude Code session",
      status: "draft",
      publishedUrl: null,
      publishedAt: null,
      updatedAt: "2026-04-12T10:00:00Z",
      daysSinceUpdate: 17,
      preview: "Notes from a weekend project that turned into the dashboard you're looking at right now.",
    },
    {
      id: 3,
      contentType: "linkedin_about",
      platform: "LinkedIn",
      title: "About section v3 — agent-orchestrator framing",
      status: "draft",
      publishedUrl: null,
      publishedAt: null,
      updatedAt: "2026-04-02T10:00:00Z",
      daysSinceUpdate: 27,
      preview: "I build tools that let agents do the boring parts — synthesis, scoring, monitoring…",
    },
    {
      id: 4,
      contentType: "linkedin_post",
      platform: "LinkedIn",
      title: "What `beacon scan` taught me about job market signal vs noise",
      status: "published",
      publishedUrl: "https://linkedin.com/posts/example",
      publishedAt: "2026-04-20T10:00:00Z",
      updatedAt: "2026-04-20T10:00:00Z",
      daysSinceUpdate: 9,
      preview: "Three weeks of running a personal CLI scanner: 412 listings, 18 worth applying to.",
    },
    {
      id: 5,
      contentType: "github_readme",
      platform: "GitHub",
      title: "beacon README — agent-first framing",
      status: "draft",
      publishedUrl: null,
      publishedAt: null,
      updatedAt: "2026-04-27T10:00:00Z",
      daysSinceUpdate: 2,
      preview: "Beacon is a tool for the agent — Claude Code is the intelligence layer.",
    },
  ],
  calendar: [
    {
      id: 1,
      title: "AI-first companies signal review",
      platform: "LinkedIn",
      contentType: "linkedin_post",
      topic: "scoring methodology",
      targetDate: "2026-05-02",
      status: "outlined",
      draftId: null,
    },
    {
      id: 2,
      title: "How I use Claude Code as a personal CTO",
      platform: "personal-site",
      contentType: "blog_post",
      topic: "workflow",
      targetDate: "2026-05-05",
      status: "drafted",
      draftId: 2,
    },
    {
      id: 3,
      title: "Job-search dashboard demo (60s)",
      platform: "LinkedIn",
      contentType: "linkedin_post",
      topic: "demo",
      targetDate: "2026-05-08",
      status: "idea",
      draftId: null,
    },
  ],
  resumes: [
    { variantLabel: "Generalist · Staff", count: 4, lastCreated: "2026-04-26T10:00:00Z", daysSince: 3 },
    { variantLabel: "AI Platform", count: 3, lastCreated: "2026-04-15T10:00:00Z", daysSince: 14 },
    { variantLabel: "Frontend Lead", count: 2, lastCreated: "2026-03-22T10:00:00Z", daysSince: 38 },
  ],
  alerts: [
    {
      kind: "stale_draft",
      title: "About section v3 — agent-orchestrator framing",
      detail: "27 days since last edit · LinkedIn About",
      cli: "beacon presence linkedin-about",
      tone: "warn",
    },
    {
      kind: "stale_resume",
      title: "Frontend Lead variant is 38 days old",
      detail: "Last refreshed before the latest beacon score recompute.",
      cli: "beacon profile resume <job_id> --pages 1",
      tone: "bad",
    },
    {
      kind: "ghost_calendar",
      title: "AI-first companies signal review · target 2026-05-02",
      detail: "Outlined but no draft created yet.",
      cli: "beacon presence blog-outline --topic 'scoring methodology'",
      tone: "warn",
    },
  ],
};

export const MOCK_SETTINGS: SettingsData = {
  scoring: [
    { key: "leadership", label: "Leadership signals", value: 0.30 },
    { key: "tool_adoption", label: "Tool adoption", value: 0.25 },
    { key: "culture", label: "Culture / hiring language", value: 0.20 },
    { key: "evidence_depth", label: "Evidence depth", value: 0.15 },
    { key: "recency", label: "Recency", value: 0.10 },
  ],
  automation: {
    lastRun: "2026-04-29T08:02:00Z",
    lastRunAge: "4h",
    lastRunType: "full",
    lastRunOk: true,
    totalRuns: 142,
    failedRuns: 6,
    lastDuration: 38.4,
  },
  notifications: [
    { channel: "Desktop (plyer)", enabled: true, detail: "On for relevance ≥ 8" },
    { channel: "Email digest", enabled: false, detail: "Configure SMTP in beacon.toml" },
    { channel: "Webhook", enabled: false, detail: "Optional: post to Slack / Discord" },
  ],
  shortcuts: [
    { combo: "G D", label: "Go to Dashboard" },
    { combo: "G J", label: "Go to Jobs" },
    { combo: "G C", label: "Go to Companies" },
    { combo: "G A", label: "Go to Applications" },
    { combo: "G O", label: "Go to Content" },
    { combo: "G S", label: "Go to Settings" },
    { combo: "⌘K", label: "Open command palette" },
  ],
  configPath: "~/.beacon/config.toml",
  dbPath: "data/beacon.db",
  isMockData: true,
};
