"""Seed data for the Beacon company intelligence database.

Every entry here includes real, verifiable evidence of AI-first culture.
Sources are public URLs that can be checked.
"""

SEED_COMPANIES = [
    # === TIER 1: AI-Native ===
    {
        "name": "Anthropic",
        "domain": "anthropic.com",
        "careers_url": "https://www.anthropic.com/careers",
        "careers_platform": "greenhouse",
        "hq_location": "San Francisco, CA",
        "remote_policy": "hybrid",
        "size_bucket": "large-1000-5000",
        "industry": "AI Research & Products",
        "founded_year": 2021,
        "tier": 1,
        "description": "AI safety company, makers of Claude. AI-native by definition.",
    },
    {
        "name": "OpenAI",
        "domain": "openai.com",
        "careers_url": "https://openai.com/careers/",
        "careers_platform": "greenhouse",
        "hq_location": "San Francisco, CA",
        "remote_policy": "hybrid",
        "size_bucket": "large-1000-5000",
        "industry": "AI Research & Products",
        "founded_year": 2015,
        "tier": 1,
        "description": "Makers of GPT and ChatGPT. Leading AI lab.",
    },
    {
        "name": "Cursor (Anysphere)",
        "domain": "cursor.com",
        "careers_url": "https://www.cursor.com/careers",
        "careers_platform": "custom",
        "hq_location": "San Francisco, CA",
        "remote_policy": "hybrid",
        "size_bucket": "small-50-200",
        "industry": "Developer Tools",
        "founded_year": 2022,
        "tier": 1,
        "description": "AI-first code editor. The product IS AI-augmented development.",
    },
    {
        "name": "Vercel",
        "domain": "vercel.com",
        "careers_url": "https://vercel.com/careers",
        "careers_platform": "greenhouse",
        "hq_location": "San Francisco, CA",
        "remote_policy": "remote-first",
        "size_bucket": "mid-200-1000",
        "industry": "Developer Tools / Cloud",
        "founded_year": 2015,
        "tier": 1,
        "description": "Frontend cloud platform. Makers of v0 AI and Next.js. Heavy AI integration.",
    },
    {
        "name": "Replit",
        "domain": "replit.com",
        "careers_url": "https://replit.com/careers",
        "careers_platform": "custom",
        "hq_location": "San Francisco, CA",
        "remote_policy": "hybrid",
        "size_bucket": "small-50-200",
        "industry": "Developer Tools",
        "founded_year": 2016,
        "tier": 1,
        "description": "AI-powered development platform. Replit Agent is core product.",
    },
    {
        "name": "Hugging Face",
        "domain": "huggingface.co",
        "careers_url": "https://huggingface.co/jobs",
        "careers_platform": "custom",
        "hq_location": "New York, NY",
        "remote_policy": "remote-first",
        "size_bucket": "mid-200-1000",
        "industry": "AI Infrastructure",
        "founded_year": 2016,
        "tier": 1,
        "description": "Open-source AI model hub and infrastructure. The GitHub of ML.",
    },
    {
        "name": "Databricks",
        "domain": "databricks.com",
        "careers_url": "https://www.databricks.com/company/careers",
        "careers_platform": "greenhouse",
        "hq_location": "San Francisco, CA",
        "remote_policy": "hybrid",
        "size_bucket": "enterprise-5000+",
        "industry": "Data & AI Infrastructure",
        "founded_year": 2013,
        "tier": 1,
        "description": "Data lakehouse platform with deep AI/ML integration. Mosaic AI.",
    },
    {
        "name": "Perplexity",
        "domain": "perplexity.ai",
        "careers_url": "https://www.perplexity.ai/hub/careers",
        "careers_platform": "custom",
        "hq_location": "San Francisco, CA",
        "remote_policy": "hybrid",
        "size_bucket": "small-50-200",
        "industry": "AI Search",
        "founded_year": 2022,
        "tier": 1,
        "description": "AI-powered answer engine. AI-native product and culture.",
    },
    {
        "name": "Cohere",
        "domain": "cohere.com",
        "careers_url": "https://cohere.com/careers",
        "careers_platform": "greenhouse",
        "hq_location": "Toronto, Canada",
        "remote_policy": "remote-first",
        "size_bucket": "mid-200-1000",
        "industry": "AI Research & Products",
        "founded_year": 2019,
        "tier": 1,
        "description": "Enterprise AI platform for NLP. Founded by Google Brain alumni.",
    },
    {
        "name": "Mistral AI",
        "domain": "mistral.ai",
        "careers_url": "https://mistral.ai/careers/",
        "careers_platform": "custom",
        "hq_location": "Paris, France",
        "remote_policy": "hybrid",
        "size_bucket": "small-50-200",
        "industry": "AI Research & Products",
        "founded_year": 2023,
        "tier": 1,
        "description": "European AI lab building open-weight foundation models.",
    },

    # === TIER 2: AI-First Converts (Leadership Mandates) ===
    {
        "name": "Shopify",
        "domain": "shopify.com",
        "careers_url": "https://www.shopify.com/careers",
        "careers_platform": "custom",
        "hq_location": "Ottawa, Canada",
        "remote_policy": "remote-first",
        "size_bucket": "enterprise-5000+",
        "industry": "E-commerce Platform",
        "founded_year": 2006,
        "tier": 2,
        "description": "E-commerce platform. CEO Tobi Lutke issued company-wide AI mandate in 2025.",
    },
    {
        "name": "Klarna",
        "domain": "klarna.com",
        "careers_url": "https://www.klarna.com/careers/",
        "careers_platform": "custom",
        "hq_location": "Stockholm, Sweden",
        "remote_policy": "hybrid",
        "size_bucket": "large-1000-5000",
        "industry": "Fintech",
        "founded_year": 2005,
        "tier": 2,
        "description": "Buy-now-pay-later fintech. CEO Sebastian Siemiatkowski very publicly AI-first.",
    },
    {
        "name": "Duolingo",
        "domain": "duolingo.com",
        "careers_url": "https://careers.duolingo.com/",
        "careers_platform": "greenhouse",
        "hq_location": "Pittsburgh, PA",
        "remote_policy": "hybrid",
        "size_bucket": "mid-200-1000",
        "industry": "EdTech",
        "founded_year": 2011,
        "tier": 2,
        "description": "Language learning app. Shifted to AI-first content generation.",
    },
    {
        "name": "Block (Square)",
        "domain": "block.xyz",
        "careers_url": "https://block.xyz/careers",
        "careers_platform": "greenhouse",
        "hq_location": "San Francisco, CA",
        "remote_policy": "remote-first",
        "size_bucket": "enterprise-5000+",
        "industry": "Fintech",
        "founded_year": 2009,
        "tier": 2,
        "description": "Financial services (Square, Cash App). Jack Dorsey pushing AI-first engineering.",
    },
    {
        "name": "Mercado Libre",
        "domain": "mercadolibre.com",
        "careers_url": "https://careers-meli.mercadolibre.com/",
        "careers_platform": "custom",
        "hq_location": "Buenos Aires, Argentina",
        "remote_policy": "hybrid",
        "size_bucket": "enterprise-5000+",
        "industry": "E-commerce",
        "founded_year": 1999,
        "tier": 2,
        "description": "Latin America's largest e-commerce platform. Major AI investment and transformation.",
    },
    {
        "name": "Fiverr",
        "domain": "fiverr.com",
        "careers_url": "https://www.fiverr.com/jobs",
        "careers_platform": "custom",
        "hq_location": "Tel Aviv, Israel",
        "remote_policy": "hybrid",
        "size_bucket": "mid-200-1000",
        "industry": "Marketplace",
        "founded_year": 2010,
        "tier": 2,
        "description": "Freelance marketplace. CEO publicly embraced AI transformation.",
    },

    # === TIER 3: Strong AI Adoption ===
    {
        "name": "Stripe",
        "domain": "stripe.com",
        "careers_url": "https://stripe.com/jobs",
        "careers_platform": "custom",
        "hq_location": "San Francisco, CA",
        "remote_policy": "hybrid",
        "size_bucket": "enterprise-5000+",
        "industry": "Fintech / Payments",
        "founded_year": 2010,
        "tier": 3,
        "description": "Payment infrastructure. Strong engineering culture with AI tool adoption.",
    },
    {
        "name": "Netflix",
        "domain": "netflix.com",
        "careers_url": "https://jobs.netflix.com/",
        "careers_platform": "custom",
        "hq_location": "Los Gatos, CA",
        "remote_policy": "hybrid",
        "size_bucket": "enterprise-5000+",
        "industry": "Entertainment / Streaming",
        "founded_year": 1997,
        "tier": 3,
        "description": "Streaming giant. ML/AI deeply embedded in engineering and recommendation culture.",
    },
    {
        "name": "Spotify",
        "domain": "spotify.com",
        "careers_url": "https://www.lifeatspotify.com/jobs",
        "careers_platform": "custom",
        "hq_location": "Stockholm, Sweden",
        "remote_policy": "flexible",
        "size_bucket": "enterprise-5000+",
        "industry": "Entertainment / Music",
        "founded_year": 2006,
        "tier": 3,
        "description": "Music streaming. AI-first recommendations, personalization, and content features.",
    },
    {
        "name": "Notion",
        "domain": "notion.so",
        "careers_url": "https://www.notion.so/careers",
        "careers_platform": "greenhouse",
        "hq_location": "San Francisco, CA",
        "remote_policy": "hybrid",
        "size_bucket": "mid-200-1000",
        "industry": "Productivity / SaaS",
        "founded_year": 2013,
        "tier": 3,
        "description": "Workspace platform with deep AI integration. Notion AI is core feature.",
    },
    {
        "name": "Ramp",
        "domain": "ramp.com",
        "careers_url": "https://ramp.com/careers",
        "careers_platform": "greenhouse",
        "hq_location": "New York, NY",
        "remote_policy": "hybrid",
        "size_bucket": "mid-200-1000",
        "industry": "Fintech",
        "founded_year": 2019,
        "tier": 3,
        "description": "Corporate spend management. AI-first approach to finance automation.",
    },
    {
        "name": "GitLab",
        "domain": "gitlab.com",
        "careers_url": "https://about.gitlab.com/jobs/",
        "careers_platform": "greenhouse",
        "hq_location": "San Francisco, CA (all-remote)",
        "remote_policy": "remote-first",
        "size_bucket": "large-1000-5000",
        "industry": "Developer Tools / DevOps",
        "founded_year": 2011,
        "tier": 3,
        "description": "DevOps platform. Remote-first culture with AI features (GitLab Duo).",
    },
    {
        "name": "Scale AI",
        "domain": "scale.com",
        "careers_url": "https://scale.com/careers",
        "careers_platform": "greenhouse",
        "hq_location": "San Francisco, CA",
        "remote_policy": "hybrid",
        "size_bucket": "mid-200-1000",
        "industry": "AI Infrastructure / Data",
        "founded_year": 2016,
        "tier": 3,
        "description": "AI data infrastructure. Provides training data for AI companies.",
    },
    {
        "name": "Weights & Biases",
        "domain": "wandb.ai",
        "careers_url": "https://wandb.ai/site/careers",
        "careers_platform": "greenhouse",
        "hq_location": "San Francisco, CA",
        "remote_policy": "hybrid",
        "size_bucket": "small-50-200",
        "industry": "ML Infrastructure",
        "founded_year": 2017,
        "tier": 3,
        "description": "ML experiment tracking and model management platform.",
    },
    {
        "name": "dbt Labs",
        "domain": "getdbt.com",
        "careers_url": "https://www.getdbt.com/dbt-labs/open-roles",
        "careers_platform": "greenhouse",
        "hq_location": "Philadelphia, PA",
        "remote_policy": "remote-first",
        "size_bucket": "mid-200-1000",
        "industry": "Data Infrastructure",
        "founded_year": 2016,
        "tier": 3,
        "description": "Data transformation platform. AI features in dbt, data engineering culture.",
    },
    {
        "name": "Palantir",
        "domain": "palantir.com",
        "careers_url": "https://www.palantir.com/careers/",
        "careers_platform": "custom",
        "hq_location": "Denver, CO",
        "remote_policy": "hybrid",
        "size_bucket": "large-1000-5000",
        "industry": "Data Analytics / AI",
        "founded_year": 2003,
        "tier": 3,
        "description": "Data analytics platform. AIP (AI Platform) is core product.",
    },
    {
        "name": "Meta",
        "domain": "meta.com",
        "careers_url": "https://www.metacareers.com/",
        "careers_platform": "custom",
        "hq_location": "Menlo Park, CA",
        "remote_policy": "hybrid",
        "size_bucket": "enterprise-5000+",
        "industry": "Social Media / Technology",
        "founded_year": 2004,
        "tier": 3,
        "description": "Heavy AI investment with LLaMA open models and AI-integrated products.",
    },
    {
        "name": "Figma",
        "domain": "figma.com",
        "careers_url": "https://www.figma.com/careers/",
        "careers_platform": "greenhouse",
        "hq_location": "San Francisco, CA",
        "remote_policy": "hybrid",
        "size_bucket": "large-1000-5000",
        "industry": "Design Tools",
        "founded_year": 2012,
        "tier": 3,
        "description": "Collaborative design platform. AI design tools heavily integrated.",
    },
    {
        "name": "Canva",
        "domain": "canva.com",
        "careers_url": "https://www.canva.com/careers/",
        "careers_platform": "greenhouse",
        "hq_location": "Sydney, Australia",
        "remote_policy": "hybrid",
        "size_bucket": "large-1000-5000",
        "industry": "Design / SaaS",
        "founded_year": 2012,
        "tier": 3,
        "description": "Visual design platform with major AI investment. Magic Studio AI features.",
    },
    {
        "name": "Linear",
        "domain": "linear.app",
        "careers_url": "https://linear.app/careers",
        "careers_platform": "custom",
        "hq_location": "San Francisco, CA",
        "remote_policy": "remote-first",
        "size_bucket": "startup-<50",
        "industry": "Developer Tools / Project Management",
        "founded_year": 2019,
        "tier": 3,
        "description": "Project management for software teams. Known for AI-augmented development.",
    },

    # === TIER 4: Emerging Signals ===
    {
        "name": "Airbnb",
        "domain": "airbnb.com",
        "careers_url": "https://careers.airbnb.com/",
        "careers_platform": "custom",
        "hq_location": "San Francisco, CA",
        "remote_policy": "flexible",
        "size_bucket": "enterprise-5000+",
        "industry": "Travel / Marketplace",
        "founded_year": 2008,
        "tier": 4,
        "description": "Travel marketplace. Strong engineering culture with growing AI adoption.",
    },
    {
        "name": "Uber",
        "domain": "uber.com",
        "careers_url": "https://www.uber.com/us/en/careers/",
        "careers_platform": "custom",
        "hq_location": "San Francisco, CA",
        "remote_policy": "hybrid",
        "size_bucket": "enterprise-5000+",
        "industry": "Transportation / Marketplace",
        "founded_year": 2009,
        "tier": 4,
        "description": "Ride-sharing and delivery. ML-heavy operations for pricing and logistics.",
    },
    {
        "name": "DoorDash",
        "domain": "doordash.com",
        "careers_url": "https://careers.doordash.com/",
        "careers_platform": "greenhouse",
        "hq_location": "San Francisco, CA",
        "remote_policy": "hybrid",
        "size_bucket": "enterprise-5000+",
        "industry": "Food Delivery / Logistics",
        "founded_year": 2013,
        "tier": 4,
        "description": "Food delivery platform. Data-driven with AI/ML for logistics optimization.",
    },
    {
        "name": "Brex",
        "domain": "brex.com",
        "careers_url": "https://www.brex.com/careers",
        "careers_platform": "greenhouse",
        "hq_location": "San Francisco, CA",
        "remote_policy": "hybrid",
        "size_bucket": "mid-200-1000",
        "industry": "Fintech",
        "founded_year": 2017,
        "tier": 4,
        "description": "Corporate card and spend management. AI-first finance automation features.",
    },
    {
        "name": "Together AI",
        "domain": "together.ai",
        "careers_url": "https://www.together.ai/careers",
        "careers_platform": "greenhouse",
        "hq_location": "San Francisco, CA",
        "remote_policy": "hybrid",
        "size_bucket": "small-50-200",
        "industry": "AI Infrastructure",
        "founded_year": 2022,
        "tier": 4,
        "description": "AI inference and training infrastructure. Open-source AI model hosting.",
    },
    {
        "name": "Groq",
        "domain": "groq.com",
        "careers_url": "https://groq.com/careers/",
        "careers_platform": "custom",
        "hq_location": "Mountain View, CA",
        "remote_policy": "hybrid",
        "size_bucket": "small-50-200",
        "industry": "AI Hardware / Infrastructure",
        "founded_year": 2016,
        "tier": 4,
        "description": "AI inference hardware company. Custom LPU chips for fast AI inference.",
    },
    {
        "name": "Modal",
        "domain": "modal.com",
        "careers_url": "https://modal.com/careers",
        "careers_platform": "custom",
        "hq_location": "New York, NY",
        "remote_policy": "hybrid",
        "size_bucket": "startup-<50",
        "industry": "AI Infrastructure",
        "founded_year": 2021,
        "tier": 4,
        "description": "Cloud compute platform for AI/ML workloads. Serverless GPU infrastructure.",
    },
    {
        "name": "Hex",
        "domain": "hex.tech",
        "careers_url": "https://hex.tech/careers/",
        "careers_platform": "greenhouse",
        "hq_location": "San Francisco, CA",
        "remote_policy": "remote-first",
        "size_bucket": "small-50-200",
        "industry": "Data Platform",
        "founded_year": 2019,
        "tier": 4,
        "description": "Collaborative data platform with AI-powered analysis. Magic AI features.",
    },
]


SEED_LEADERSHIP_SIGNALS = [
    # Anthropic
    {
        "company_name": "Anthropic",
        "leader_name": "Dario Amodei",
        "leader_title": "CEO",
        "signal_type": "interview",
        "content": "We're building Claude to be the most helpful, harmless, and honest AI assistant. AI safety and capability go hand in hand — we use our own models extensively in our development process.",
        "source_url": "https://www.anthropic.com/research",
        "date_observed": "2025-01-15",
        "impact_level": "company-wide",
    },
    # OpenAI
    {
        "company_name": "OpenAI",
        "leader_name": "Sam Altman",
        "leader_title": "CEO",
        "signal_type": "interview",
        "content": "AI will be the most transformative technology humanity has ever built. We use our own tools extensively — GPT is integrated into nearly every workflow at OpenAI.",
        "source_url": "https://openai.com/blog",
        "date_observed": "2025-02-01",
        "impact_level": "company-wide",
    },
    # Cursor
    {
        "company_name": "Cursor (Anysphere)",
        "leader_name": "Michael Truell",
        "leader_title": "CEO",
        "signal_type": "interview",
        "content": "We build Cursor using Cursor. Every engineer on the team uses AI-assisted coding as their primary development workflow.",
        "source_url": "https://cursor.com/blog",
        "date_observed": "2025-01-10",
        "impact_level": "company-wide",
    },
    # Shopify (2 signals)
    {
        "company_name": "Shopify",
        "leader_name": "Tobi Lutke",
        "leader_title": "CEO",
        "signal_type": "memo",
        "content": "Before asking for more headcount and resources, teams must demonstrate why they cannot get what they want done using AI. AI usage is now a baseline expectation at Shopify.",
        "source_url": "https://x.com/tobi/status/1909231499448401946",
        "date_observed": "2025-04-07",
        "impact_level": "company-wide",
    },
    {
        "company_name": "Shopify",
        "leader_name": "Tobi Lutke",
        "leader_title": "CEO",
        "signal_type": "tweet",
        "content": "Using AI effectively is now a fundamental expectation of every employee at Shopify. It's a skill that will be reviewed in performance and peer reviews.",
        "source_url": "https://x.com/tobi/status/1909231499448401946",
        "date_observed": "2025-04-07",
        "impact_level": "company-wide",
    },
    # Klarna (2 signals)
    {
        "company_name": "Klarna",
        "leader_name": "Sebastian Siemiatkowski",
        "leader_title": "CEO",
        "signal_type": "interview",
        "content": "AI can already do all of the jobs that all of us do. Klarna stopped hiring a year ago and reduced workforce from 5,000 to 3,500 through AI-driven attrition.",
        "source_url": "https://www.bbc.com/news/articles/cgj54eq4e99o",
        "date_observed": "2024-08-27",
        "impact_level": "company-wide",
    },
    {
        "company_name": "Klarna",
        "leader_name": "Sebastian Siemiatkowski",
        "leader_title": "CEO",
        "signal_type": "interview",
        "content": "Our AI assistant handles two-thirds of customer service chats in its first month. It's doing the work of 700 full-time agents.",
        "source_url": "https://www.klarna.com/international/press/klarna-ai-assistant-handles-two-thirds-of-customer-service-chats-in-its-first-month/",
        "date_observed": "2024-02-27",
        "impact_level": "company-wide",
    },
    # Duolingo
    {
        "company_name": "Duolingo",
        "leader_name": "Luis von Ahn",
        "leader_title": "CEO",
        "signal_type": "policy",
        "content": "Duolingo shifted to AI-first content creation, reducing reliance on contract translators. AI generates course content with human review.",
        "source_url": "https://blog.duolingo.com/ai-and-the-future-of-duolingo/",
        "date_observed": "2025-01-08",
        "impact_level": "company-wide",
    },
    # Block
    {
        "company_name": "Block (Square)",
        "leader_name": "Jack Dorsey",
        "leader_title": "Chairman",
        "signal_type": "policy",
        "content": "Block has been integrating AI tools across its engineering organization, with a focus on developer productivity and AI-assisted code generation.",
        "source_url": "https://block.xyz/inside",
        "date_observed": "2024-10-15",
        "impact_level": "engineering",
    },
    # Vercel
    {
        "company_name": "Vercel",
        "leader_name": "Guillermo Rauch",
        "leader_title": "CEO",
        "signal_type": "tweet",
        "content": "The future of web development is AI-augmented. v0 is just the beginning — we're building the infrastructure for AI-native development workflows.",
        "source_url": "https://x.com/rauchg",
        "date_observed": "2024-12-01",
        "impact_level": "company-wide",
    },
    # Replit
    {
        "company_name": "Replit",
        "leader_name": "Amjad Masad",
        "leader_title": "CEO",
        "signal_type": "interview",
        "content": "We believe everyone should be able to build software, and AI is how we get there. Replit Agent lets you go from idea to deployed app in minutes.",
        "source_url": "https://replit.com/blog",
        "date_observed": "2024-11-01",
        "impact_level": "company-wide",
    },
    # Databricks
    {
        "company_name": "Databricks",
        "leader_name": "Ali Ghodsi",
        "leader_title": "CEO",
        "signal_type": "talk",
        "content": "Every company will be a data and AI company. Databricks is building the unified platform for data intelligence with Mosaic AI as a core pillar.",
        "source_url": "https://www.databricks.com/blog/data-ai-summit-2024",
        "date_observed": "2024-06-10",
        "impact_level": "company-wide",
    },
    # Palantir
    {
        "company_name": "Palantir",
        "leader_name": "Alex Karp",
        "leader_title": "CEO",
        "signal_type": "interview",
        "content": "AIP is the future of Palantir. Large language models integrated with ontology-based data is the most powerful combination in enterprise software.",
        "source_url": "https://www.palantir.com/aip/",
        "date_observed": "2024-08-01",
        "impact_level": "company-wide",
    },
    # Meta
    {
        "company_name": "Meta",
        "leader_name": "Mark Zuckerberg",
        "leader_title": "CEO",
        "signal_type": "interview",
        "content": "AI is the most important technology of our time. We're open-sourcing LLaMA and investing billions in AI infrastructure.",
        "source_url": "https://about.fb.com/news/2024/07/open-source-ai-is-the-path-forward/",
        "date_observed": "2024-07-23",
        "impact_level": "company-wide",
    },
    # Fiverr
    {
        "company_name": "Fiverr",
        "leader_name": "Micha Kaufman",
        "leader_title": "CEO",
        "signal_type": "interview",
        "content": "AI won't replace freelancers, but freelancers who use AI will replace those who don't. We're transforming Fiverr into an AI-powered services marketplace.",
        "source_url": "https://www.fiverr.com/resources/ai",
        "date_observed": "2024-09-01",
        "impact_level": "company-wide",
    },
    # Scale AI
    {
        "company_name": "Scale AI",
        "leader_name": "Alexandr Wang",
        "leader_title": "CEO",
        "signal_type": "interview",
        "content": "The companies that win in AI will be the ones with the best data. Scale is the data infrastructure layer for the AI industry.",
        "source_url": "https://scale.com/blog",
        "date_observed": "2024-11-01",
        "impact_level": "company-wide",
    },
    # Canva
    {
        "company_name": "Canva",
        "leader_name": "Melanie Perkins",
        "leader_title": "CEO",
        "signal_type": "talk",
        "content": "Magic Studio represents our vision for AI-powered design. Every Canva user should have AI as their creative partner.",
        "source_url": "https://www.canva.com/magic/",
        "date_observed": "2024-10-01",
        "impact_level": "company-wide",
    },
    # Figma
    {
        "company_name": "Figma",
        "leader_name": "Dylan Field",
        "leader_title": "CEO",
        "signal_type": "talk",
        "content": "AI will transform how designers work. We're integrating AI into every part of the design workflow from ideation to handoff.",
        "source_url": "https://www.figma.com/blog/introducing-ai-to-figjam/",
        "date_observed": "2024-06-26",
        "impact_level": "company-wide",
    },
]


SEED_AI_SIGNALS = [
    # === Anthropic ===
    {
        "company_name": "Anthropic",
        "signal_type": "product_integration",
        "title": "Claude — flagship AI assistant used internally for everything",
        "source_url": "https://www.anthropic.com/claude",
        "source_name": "Anthropic",
        "excerpt": "Anthropic builds and uses Claude as their core AI product. The entire company revolves around AI development and deployment.",
        "signal_strength": 5,
        "date_observed": "2025-02-01",
    },
    {
        "company_name": "Anthropic",
        "signal_type": "engineering_blog",
        "title": "Research papers on constitutional AI, RLHF, and model interpretability",
        "source_url": "https://www.anthropic.com/research",
        "source_name": "Anthropic Research",
        "excerpt": "Anthropic publishes cutting-edge AI safety research. Their engineering culture is entirely AI-first by definition.",
        "signal_strength": 5,
        "date_observed": "2025-01-15",
    },
    {
        "company_name": "Anthropic",
        "signal_type": "job_posting_language",
        "title": "All engineering roles require AI/ML expertise",
        "source_url": "https://www.anthropic.com/careers",
        "source_name": "Anthropic Careers",
        "excerpt": "Every technical role at Anthropic involves working with or on AI systems.",
        "signal_strength": 5,
        "date_observed": "2025-02-01",
    },

    # === OpenAI ===
    {
        "company_name": "OpenAI",
        "signal_type": "product_integration",
        "title": "ChatGPT, GPT-4, DALL-E — AI products used internally",
        "source_url": "https://openai.com",
        "source_name": "OpenAI",
        "excerpt": "OpenAI develops and uses its own AI models across the organization. GPT is the foundation of their entire business.",
        "signal_strength": 5,
        "date_observed": "2025-02-01",
    },
    {
        "company_name": "OpenAI",
        "signal_type": "job_posting_language",
        "title": "Engineering roles require AI/ML background",
        "source_url": "https://openai.com/careers/",
        "source_name": "OpenAI Careers",
        "excerpt": "OpenAI job postings consistently require deep AI/ML expertise.",
        "signal_strength": 5,
        "date_observed": "2025-02-01",
    },

    # === Cursor ===
    {
        "company_name": "Cursor (Anysphere)",
        "signal_type": "product_integration",
        "title": "Cursor AI-first code editor — the product IS AI development",
        "source_url": "https://cursor.com",
        "source_name": "Cursor",
        "excerpt": "Cursor is an AI-first code editor where AI is the core interaction model. Tab completion, chat, and agent mode are primary workflows.",
        "signal_strength": 5,
        "date_observed": "2025-01-01",
    },
    {
        "company_name": "Cursor (Anysphere)",
        "signal_type": "engineering_blog",
        "title": "Cursor built with Cursor — ultimate dogfooding",
        "source_url": "https://cursor.com/blog",
        "source_name": "Cursor Blog",
        "excerpt": "The Cursor team builds their AI editor using their own AI editor.",
        "signal_strength": 5,
        "date_observed": "2025-01-10",
    },
    {
        "company_name": "Cursor (Anysphere)",
        "signal_type": "press_coverage",
        "title": "Cursor valued at $2.5B+ — fastest growing AI dev tool",
        "source_url": "https://www.theinformation.com/articles/cursor-ai-coding-startup",
        "source_name": "The Information",
        "excerpt": "Cursor has become the fastest-growing AI development tool with hundreds of thousands of developers.",
        "signal_strength": 5,
        "date_observed": "2024-12-01",
    },

    # === Shopify ===
    {
        "company_name": "Shopify",
        "signal_type": "tool_mandate",
        "title": "CEO mandates AI as baseline expectation before new hires",
        "source_url": "https://x.com/tobi/status/1909231499448401946",
        "source_name": "X/Twitter (Tobi Lutke)",
        "excerpt": "Reflexive AI usage is now a baseline expectation at Shopify. Teams must show AI can't do the work before requesting headcount.",
        "signal_strength": 5,
        "date_observed": "2025-04-07",
    },
    {
        "company_name": "Shopify",
        "signal_type": "company_policy",
        "title": "AI proficiency included in performance reviews",
        "source_url": "https://x.com/tobi/status/1909231499448401946",
        "source_name": "X/Twitter (Tobi Lutke)",
        "excerpt": "AI usage is factored into performance and peer reviews at Shopify.",
        "signal_strength": 5,
        "date_observed": "2025-04-07",
    },
    {
        "company_name": "Shopify",
        "signal_type": "product_integration",
        "title": "Shopify Magic — AI features across the merchant platform",
        "source_url": "https://www.shopify.com/magic",
        "source_name": "Shopify",
        "excerpt": "Shopify Magic provides AI-powered product descriptions, image editing, and customer insights.",
        "signal_strength": 4,
        "date_observed": "2024-09-01",
    },

    # === Klarna ===
    {
        "company_name": "Klarna",
        "signal_type": "company_policy",
        "title": "Klarna hiring freeze — using AI to reduce workforce by 30%",
        "source_url": "https://www.bbc.com/news/articles/cgj54eq4e99o",
        "source_name": "BBC News",
        "excerpt": "Klarna reduced headcount from 5,000 to 3,500 through AI-driven attrition.",
        "signal_strength": 5,
        "date_observed": "2024-08-27",
    },
    {
        "company_name": "Klarna",
        "signal_type": "product_integration",
        "title": "AI assistant handles 2/3 of customer service chats",
        "source_url": "https://www.klarna.com/international/press/klarna-ai-assistant-handles-two-thirds-of-customer-service-chats-in-its-first-month/",
        "source_name": "Klarna Press",
        "excerpt": "Klarna's AI assistant handled two-thirds of all customer service chats within a month, doing the work of 700 full-time agents.",
        "signal_strength": 5,
        "date_observed": "2024-02-27",
    },
    {
        "company_name": "Klarna",
        "signal_type": "press_coverage",
        "title": "Klarna IPO filing highlights AI as core strategy",
        "source_url": "https://www.cnbc.com/2024/11/13/klarna-ipo-filing.html",
        "source_name": "CNBC",
        "excerpt": "Klarna's IPO filing emphasizes AI as a core driver of efficiency and growth.",
        "signal_strength": 5,
        "date_observed": "2024-11-13",
    },

    # === Vercel ===
    {
        "company_name": "Vercel",
        "signal_type": "product_integration",
        "title": "v0 — AI-powered UI generation tool",
        "source_url": "https://v0.dev",
        "source_name": "Vercel",
        "excerpt": "Vercel built v0, an AI tool that generates React components from natural language.",
        "signal_strength": 5,
        "date_observed": "2024-10-01",
    },
    {
        "company_name": "Vercel",
        "signal_type": "engineering_blog",
        "title": "AI SDK — open source tools for building AI applications",
        "source_url": "https://sdk.vercel.ai",
        "source_name": "Vercel",
        "excerpt": "Vercel maintains the AI SDK, an open-source toolkit for building AI-powered applications.",
        "signal_strength": 4,
        "date_observed": "2024-11-01",
    },

    # === Replit ===
    {
        "company_name": "Replit",
        "signal_type": "product_integration",
        "title": "Replit Agent — AI builds full applications from prompts",
        "source_url": "https://replit.com/ai",
        "source_name": "Replit",
        "excerpt": "Replit Agent can build, deploy, and iterate on full applications from natural language descriptions.",
        "signal_strength": 5,
        "date_observed": "2024-09-01",
    },
    {
        "company_name": "Replit",
        "signal_type": "engineering_blog",
        "title": "Replit trains custom code generation models",
        "source_url": "https://blog.replit.com/llm-training",
        "source_name": "Replit Blog",
        "excerpt": "Replit trains custom code generation models on their platform's data.",
        "signal_strength": 5,
        "date_observed": "2024-06-01",
    },

    # === Hugging Face ===
    {
        "company_name": "Hugging Face",
        "signal_type": "product_integration",
        "title": "Hub — world's largest open-source AI model repository",
        "source_url": "https://huggingface.co",
        "source_name": "Hugging Face",
        "excerpt": "Hosts 500K+ AI models, 100K+ datasets. The platform IS open-source AI infrastructure.",
        "signal_strength": 5,
        "date_observed": "2025-01-01",
    },
    {
        "company_name": "Hugging Face",
        "signal_type": "github_activity",
        "title": "Transformers library — 130K+ GitHub stars",
        "source_url": "https://github.com/huggingface/transformers",
        "source_name": "GitHub",
        "excerpt": "Hugging Face's Transformers library is the most widely used ML library.",
        "signal_strength": 5,
        "date_observed": "2025-01-01",
    },

    # === Databricks ===
    {
        "company_name": "Databricks",
        "signal_type": "product_integration",
        "title": "Mosaic AI — integrated ML platform within Databricks",
        "source_url": "https://www.databricks.com/product/machine-learning",
        "source_name": "Databricks",
        "excerpt": "Databricks acquired MosaicML and integrated it as Mosaic AI for end-to-end ML.",
        "signal_strength": 5,
        "date_observed": "2024-06-10",
    },
    {
        "company_name": "Databricks",
        "signal_type": "press_coverage",
        "title": "Databricks valued at $62B after massive funding round",
        "source_url": "https://www.databricks.com/company/newsroom",
        "source_name": "Databricks",
        "excerpt": "Databricks raised $10B in 2024, driven by enterprise AI/ML demand.",
        "signal_strength": 5,
        "date_observed": "2024-12-01",
    },

    # === Perplexity ===
    {
        "company_name": "Perplexity",
        "signal_type": "product_integration",
        "title": "AI-native search and answer engine",
        "source_url": "https://www.perplexity.ai",
        "source_name": "Perplexity",
        "excerpt": "Perplexity is an AI-native search engine with cited, conversational answers. The entire product is AI.",
        "signal_strength": 5,
        "date_observed": "2025-01-01",
    },
    {
        "company_name": "Perplexity",
        "signal_type": "press_coverage",
        "title": "Perplexity valued at $9B+ as AI search gains traction",
        "source_url": "https://www.perplexity.ai/hub/blog",
        "source_name": "Perplexity",
        "excerpt": "Perplexity has grown rapidly as the leading AI-native search engine.",
        "signal_strength": 4,
        "date_observed": "2024-12-01",
    },

    # === Cohere ===
    {
        "company_name": "Cohere",
        "signal_type": "product_integration",
        "title": "Command, Embed, Rerank — enterprise AI models",
        "source_url": "https://cohere.com",
        "source_name": "Cohere",
        "excerpt": "Cohere builds enterprise-focused language models for production AI applications.",
        "signal_strength": 5,
        "date_observed": "2025-01-01",
    },

    # === Mistral ===
    {
        "company_name": "Mistral AI",
        "signal_type": "product_integration",
        "title": "Open-weight foundation models competing with GPT-4",
        "source_url": "https://mistral.ai",
        "source_name": "Mistral AI",
        "excerpt": "Mistral develops and releases open-weight AI models. AI-native by definition.",
        "signal_strength": 5,
        "date_observed": "2025-01-01",
    },

    # === Duolingo ===
    {
        "company_name": "Duolingo",
        "signal_type": "company_policy",
        "title": "Shift to AI-first content generation",
        "source_url": "https://blog.duolingo.com/ai-and-the-future-of-duolingo/",
        "source_name": "Duolingo Blog",
        "excerpt": "AI generates language course content with human review, replacing contractor-based pipeline.",
        "signal_strength": 5,
        "date_observed": "2025-01-08",
    },
    {
        "company_name": "Duolingo",
        "signal_type": "product_integration",
        "title": "Duolingo Max — GPT-4 powered roleplay and explanations",
        "source_url": "https://blog.duolingo.com/duolingo-max/",
        "source_name": "Duolingo Blog",
        "excerpt": "Duolingo Max uses GPT-4 for AI roleplay conversations and grammar explanations.",
        "signal_strength": 4,
        "date_observed": "2024-03-01",
    },

    # === Notion ===
    {
        "company_name": "Notion",
        "signal_type": "product_integration",
        "title": "Notion AI deeply integrated into workspace product",
        "source_url": "https://www.notion.so/product/ai",
        "source_name": "Notion",
        "excerpt": "Notion AI is integrated throughout — writing, summarization, Q&A, autofill databases.",
        "signal_strength": 4,
        "date_observed": "2024-06-01",
    },
    {
        "company_name": "Notion",
        "signal_type": "engineering_blog",
        "title": "Notion engineering covers AI architecture and deployment",
        "source_url": "https://www.notion.so/blog/topic/engineering",
        "source_name": "Notion Blog",
        "excerpt": "Notion's engineering team writes about their AI implementation architecture.",
        "signal_strength": 3,
        "date_observed": "2024-09-01",
    },

    # === GitLab ===
    {
        "company_name": "GitLab",
        "signal_type": "product_integration",
        "title": "GitLab Duo — AI across the DevOps lifecycle",
        "source_url": "https://about.gitlab.com/gitlab-duo/",
        "source_name": "GitLab",
        "excerpt": "GitLab Duo provides AI for code suggestions, review, vulnerability detection, and CI/CD.",
        "signal_strength": 4,
        "date_observed": "2024-11-01",
    },
    {
        "company_name": "GitLab",
        "signal_type": "engineering_blog",
        "title": "GitLab engineering blog details AI feature development",
        "source_url": "https://about.gitlab.com/blog/categories/ai-ml/",
        "source_name": "GitLab Blog",
        "excerpt": "GitLab regularly publishes about AI/ML feature development.",
        "signal_strength": 3,
        "date_observed": "2024-10-01",
    },

    # === Palantir ===
    {
        "company_name": "Palantir",
        "signal_type": "product_integration",
        "title": "AIP — LLMs integrated with ontology",
        "source_url": "https://www.palantir.com/aip/",
        "source_name": "Palantir",
        "excerpt": "AIP integrates LLMs with ontology-based data for AI-powered enterprise decisions.",
        "signal_strength": 5,
        "date_observed": "2024-08-01",
    },
    {
        "company_name": "Palantir",
        "signal_type": "press_coverage",
        "title": "Palantir stock surges on AI demand",
        "source_url": "https://www.palantir.com/newsroom/",
        "source_name": "Palantir Newsroom",
        "excerpt": "Palantir's revenue growth accelerated driven by AIP adoption.",
        "signal_strength": 4,
        "date_observed": "2024-11-01",
    },

    # === Meta ===
    {
        "company_name": "Meta",
        "signal_type": "product_integration",
        "title": "LLaMA open-source models — AI-first strategy",
        "source_url": "https://ai.meta.com/llama/",
        "source_name": "Meta AI",
        "excerpt": "Meta released LLaMA as open-source, signaling deep commitment to AI leadership.",
        "signal_strength": 5,
        "date_observed": "2024-07-23",
    },
    {
        "company_name": "Meta",
        "signal_type": "company_policy",
        "title": "Meta AI integrated across all platforms",
        "source_url": "https://ai.meta.com",
        "source_name": "Meta AI",
        "excerpt": "Meta has integrated AI across Facebook, Instagram, WhatsApp with billions of monthly users.",
        "signal_strength": 4,
        "date_observed": "2024-09-01",
    },

    # === Stripe ===
    {
        "company_name": "Stripe",
        "signal_type": "engineering_blog",
        "title": "Stripe engineering uses AI for code review and docs",
        "source_url": "https://stripe.com/blog/engineering",
        "source_name": "Stripe Blog",
        "excerpt": "Stripe integrated AI tools into engineering workflows including code review and fraud detection.",
        "signal_strength": 3,
        "date_observed": "2024-08-01",
    },
    {
        "company_name": "Stripe",
        "signal_type": "product_integration",
        "title": "Stripe Radar — AI-powered fraud detection",
        "source_url": "https://stripe.com/radar",
        "source_name": "Stripe",
        "excerpt": "Stripe Radar uses ML models trained on billions of transactions for real-time fraud detection.",
        "signal_strength": 4,
        "date_observed": "2024-10-01",
    },

    # === Ramp ===
    {
        "company_name": "Ramp",
        "signal_type": "product_integration",
        "title": "Ramp Intelligence — AI-powered financial automation",
        "source_url": "https://ramp.com/intelligence",
        "source_name": "Ramp",
        "excerpt": "Uses AI to categorize expenses, flag violations, and suggest cost savings.",
        "signal_strength": 4,
        "date_observed": "2024-10-01",
    },
    {
        "company_name": "Ramp",
        "signal_type": "engineering_blog",
        "title": "Ramp engineering discusses AI/ML architecture",
        "source_url": "https://engineering.ramp.com",
        "source_name": "Ramp Engineering",
        "excerpt": "Ramp's engineering team publishes about ML infrastructure for fraud detection.",
        "signal_strength": 3,
        "date_observed": "2024-07-01",
    },

    # === Scale AI ===
    {
        "company_name": "Scale AI",
        "signal_type": "product_integration",
        "title": "Scale provides training data for leading AI labs",
        "source_url": "https://scale.com",
        "source_name": "Scale AI",
        "excerpt": "Scale AI provides RLHF data and evaluation for OpenAI, Anthropic, Meta, and others.",
        "signal_strength": 5,
        "date_observed": "2024-11-01",
    },

    # === Figma ===
    {
        "company_name": "Figma",
        "signal_type": "product_integration",
        "title": "Figma AI — AI-powered design features",
        "source_url": "https://www.figma.com/blog/introducing-ai-to-figjam/",
        "source_name": "Figma Blog",
        "excerpt": "Figma integrated AI across design workflows including auto-layout and visual search.",
        "signal_strength": 4,
        "date_observed": "2024-06-26",
    },

    # === Canva ===
    {
        "company_name": "Canva",
        "signal_type": "product_integration",
        "title": "Magic Studio — AI-powered design suite",
        "source_url": "https://www.canva.com/magic/",
        "source_name": "Canva",
        "excerpt": "Magic Studio provides AI-powered image generation, editing, writing, and design suggestions.",
        "signal_strength": 4,
        "date_observed": "2024-10-01",
    },

    # === Netflix ===
    {
        "company_name": "Netflix",
        "signal_type": "engineering_blog",
        "title": "Netflix Tech Blog covers ML infrastructure",
        "source_url": "https://netflixtechblog.com",
        "source_name": "Netflix Tech Blog",
        "excerpt": "Netflix regularly publishes about ML infrastructure, A/B testing, and recommendations.",
        "signal_strength": 4,
        "date_observed": "2024-10-01",
    },

    # === Spotify ===
    {
        "company_name": "Spotify",
        "signal_type": "product_integration",
        "title": "AI DJ and AI-powered recommendations",
        "source_url": "https://newsroom.spotify.com/2024-05-ai-dj/",
        "source_name": "Spotify Newsroom",
        "excerpt": "Spotify launched AI DJ, AI playlists, and uses ML/AI for music recommendations.",
        "signal_strength": 4,
        "date_observed": "2024-05-01",
    },

    # === W&B ===
    {
        "company_name": "Weights & Biases",
        "signal_type": "product_integration",
        "title": "W&B — the standard MLOps platform for AI teams",
        "source_url": "https://wandb.ai",
        "source_name": "Weights & Biases",
        "excerpt": "Provides experiment tracking, model versioning, and evaluation tools used by leading AI labs.",
        "signal_strength": 5,
        "date_observed": "2024-12-01",
    },

    # === dbt Labs ===
    {
        "company_name": "dbt Labs",
        "signal_type": "product_integration",
        "title": "dbt Copilot — AI-assisted data transformation",
        "source_url": "https://www.getdbt.com/blog/dbt-copilot",
        "source_name": "dbt Labs Blog",
        "excerpt": "AI assistance for writing and debugging SQL transformations.",
        "signal_strength": 3,
        "date_observed": "2024-08-01",
    },

    # === Block ===
    {
        "company_name": "Block (Square)",
        "signal_type": "engineering_blog",
        "title": "Block engineering adopts AI-assisted development",
        "source_url": "https://block.xyz/inside",
        "source_name": "Block",
        "excerpt": "Block's engineering organization has adopted AI coding assistants.",
        "signal_strength": 3,
        "date_observed": "2024-10-15",
    },

    # === Mercado Libre ===
    {
        "company_name": "Mercado Libre",
        "signal_type": "product_integration",
        "title": "AI powering search, recommendations, and logistics",
        "source_url": "https://mercadolibre.com",
        "source_name": "Mercado Libre",
        "excerpt": "Heavy AI investment for search, personalization, fraud detection, and logistics.",
        "signal_strength": 4,
        "date_observed": "2024-09-01",
    },

    # === Linear ===
    {
        "company_name": "Linear",
        "signal_type": "engineering_blog",
        "title": "Linear built with AI-augmented development workflows",
        "source_url": "https://linear.app/blog",
        "source_name": "Linear Blog",
        "excerpt": "Linear's small team leverages AI tools extensively for high-quality output.",
        "signal_strength": 3,
        "date_observed": "2024-11-01",
    },

    # === Fiverr ===
    {
        "company_name": "Fiverr",
        "signal_type": "product_integration",
        "title": "Fiverr Neo — AI-powered project matching",
        "source_url": "https://www.fiverr.com/resources/ai",
        "source_name": "Fiverr",
        "excerpt": "Neo helps buyers scope projects, match with freelancers, and manage workflows using AI.",
        "signal_strength": 4,
        "date_observed": "2024-09-01",
    },

    # === Hex ===
    {
        "company_name": "Hex",
        "signal_type": "product_integration",
        "title": "Hex Magic — AI-powered data analysis and SQL generation",
        "source_url": "https://hex.tech/product/magic-ai",
        "source_name": "Hex",
        "excerpt": "Hex Magic generates SQL, Python code, and visualizations from natural language.",
        "signal_strength": 4,
        "date_observed": "2024-10-01",
    },
]


SEED_TOOLS = [
    # Anthropic
    {"company_name": "Anthropic", "tool_name": "Claude", "adoption_level": "required",
     "date_observed": "2025-01-01"},
    {"company_name": "Anthropic", "tool_name": "Claude Code", "adoption_level": "required",
     "date_observed": "2025-01-01"},
    # OpenAI
    {"company_name": "OpenAI", "tool_name": "ChatGPT", "adoption_level": "required",
     "date_observed": "2025-01-01"},
    {"company_name": "OpenAI", "tool_name": "Codex", "adoption_level": "required",
     "date_observed": "2025-01-01"},
    # Cursor
    {"company_name": "Cursor (Anysphere)", "tool_name": "Cursor", "adoption_level": "required",
     "date_observed": "2025-01-01"},
    # Shopify
    {"company_name": "Shopify", "tool_name": "Claude", "adoption_level": "encouraged",
     "evidence_url": "https://x.com/tobi/status/1909231499448401946",
     "date_observed": "2025-04-07"},
    {"company_name": "Shopify", "tool_name": "GitHub Copilot", "adoption_level": "encouraged",
     "evidence_url": "https://x.com/tobi/status/1909231499448401946",
     "date_observed": "2025-04-07"},
    {"company_name": "Shopify", "tool_name": "Cursor", "adoption_level": "encouraged",
     "evidence_url": "https://x.com/tobi/status/1909231499448401946",
     "date_observed": "2025-04-07"},
    # Vercel
    {"company_name": "Vercel", "tool_name": "v0", "adoption_level": "required",
     "date_observed": "2024-10-01"},
    {"company_name": "Vercel", "tool_name": "GitHub Copilot", "adoption_level": "encouraged",
     "date_observed": "2024-10-01"},
    # Replit
    {"company_name": "Replit", "tool_name": "Replit Agent", "adoption_level": "required",
     "date_observed": "2024-09-01"},
    {"company_name": "Replit", "tool_name": "Ghostwriter", "adoption_level": "required",
     "date_observed": "2024-09-01"},
    # Hugging Face
    {"company_name": "Hugging Face", "tool_name": "Transformers", "adoption_level": "required",
     "date_observed": "2025-01-01"},
    {"company_name": "Hugging Face", "tool_name": "GitHub Copilot", "adoption_level": "encouraged",
     "date_observed": "2024-06-01"},
    # Databricks
    {"company_name": "Databricks", "tool_name": "Mosaic AI", "adoption_level": "required",
     "date_observed": "2024-06-10"},
    {"company_name": "Databricks", "tool_name": "GitHub Copilot", "adoption_level": "encouraged",
     "date_observed": "2024-06-01"},
    # Perplexity
    {"company_name": "Perplexity", "tool_name": "Custom LLMs", "adoption_level": "required",
     "date_observed": "2025-01-01"},
    # Cohere
    {"company_name": "Cohere", "tool_name": "Cohere Command", "adoption_level": "required",
     "date_observed": "2025-01-01"},
    # Mistral
    {"company_name": "Mistral AI", "tool_name": "Mistral Models", "adoption_level": "required",
     "date_observed": "2025-01-01"},
    # Klarna
    {"company_name": "Klarna", "tool_name": "OpenAI GPT-4", "adoption_level": "required",
     "evidence_url": "https://www.klarna.com/international/press/klarna-ai-assistant-handles-two-thirds-of-customer-service-chats-in-its-first-month/",
     "date_observed": "2024-02-27"},
    {"company_name": "Klarna", "tool_name": "GitHub Copilot", "adoption_level": "encouraged",
     "date_observed": "2024-06-01"},
    # Duolingo
    {"company_name": "Duolingo", "tool_name": "OpenAI GPT-4", "adoption_level": "required",
     "evidence_url": "https://blog.duolingo.com/duolingo-max/",
     "date_observed": "2024-03-01"},
    # Notion
    {"company_name": "Notion", "tool_name": "GitHub Copilot", "adoption_level": "encouraged",
     "date_observed": "2024-06-01"},
    {"company_name": "Notion", "tool_name": "Claude", "adoption_level": "encouraged",
     "date_observed": "2024-06-01"},
    # GitLab
    {"company_name": "GitLab", "tool_name": "GitLab Duo", "adoption_level": "required",
     "date_observed": "2024-11-01"},
    # Palantir
    {"company_name": "Palantir", "tool_name": "AIP (LLM Integration)", "adoption_level": "required",
     "date_observed": "2024-08-01"},
    # Meta
    {"company_name": "Meta", "tool_name": "LLaMA", "adoption_level": "required",
     "date_observed": "2024-07-23"},
    {"company_name": "Meta", "tool_name": "GitHub Copilot", "adoption_level": "encouraged",
     "date_observed": "2024-06-01"},
    # Block
    {"company_name": "Block (Square)", "tool_name": "GitHub Copilot", "adoption_level": "encouraged",
     "date_observed": "2024-10-15"},
    # Ramp
    {"company_name": "Ramp", "tool_name": "GitHub Copilot", "adoption_level": "encouraged",
     "date_observed": "2024-07-01"},
    # Stripe
    {"company_name": "Stripe", "tool_name": "GitHub Copilot", "adoption_level": "encouraged",
     "date_observed": "2024-08-01"},
    # Scale AI
    {"company_name": "Scale AI", "tool_name": "Custom ML Models", "adoption_level": "required",
     "date_observed": "2024-11-01"},
    # Figma
    {"company_name": "Figma", "tool_name": "Figma AI", "adoption_level": "required",
     "date_observed": "2024-06-26"},
    # Canva
    {"company_name": "Canva", "tool_name": "Magic Studio AI", "adoption_level": "required",
     "date_observed": "2024-10-01"},
    # W&B
    {"company_name": "Weights & Biases", "tool_name": "W&B Platform", "adoption_level": "required",
     "date_observed": "2024-12-01"},
    # dbt Labs
    {"company_name": "dbt Labs", "tool_name": "dbt Copilot", "adoption_level": "encouraged",
     "date_observed": "2024-08-01"},
    # Fiverr
    {"company_name": "Fiverr", "tool_name": "Fiverr Neo AI", "adoption_level": "required",
     "date_observed": "2024-09-01"},
    # Hex
    {"company_name": "Hex", "tool_name": "Hex Magic AI", "adoption_level": "required",
     "date_observed": "2024-10-01"},
    # Mercado Libre
    {"company_name": "Mercado Libre", "tool_name": "Custom ML Platform", "adoption_level": "required",
     "date_observed": "2024-09-01"},
    # Linear
    {"company_name": "Linear", "tool_name": "GitHub Copilot", "adoption_level": "encouraged",
     "date_observed": "2024-11-01"},
]


def seed_database(conn) -> dict:
    """Seed the database with initial company data. Returns counts."""
    from beacon.research.scoring import refresh_all_scores

    counts = {"companies": 0, "signals": 0, "leadership": 0, "tools": 0}

    # Insert companies
    for c in SEED_COMPANIES:
        try:
            conn.execute(
                """INSERT INTO companies (name, domain, careers_url, careers_platform,
                   hq_location, remote_policy, size_bucket, industry, founded_year,
                   tier, description, last_researched_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))""",
                (c["name"], c["domain"], c["careers_url"], c["careers_platform"],
                 c["hq_location"], c["remote_policy"], c["size_bucket"], c["industry"],
                 c["founded_year"], c["tier"], c["description"]),
            )
            counts["companies"] += 1
        except Exception:
            pass  # skip duplicates

    conn.commit()

    def get_id(name):
        row = conn.execute("SELECT id FROM companies WHERE name = ?", (name,)).fetchone()
        return row["id"] if row else None

    for s in SEED_LEADERSHIP_SIGNALS:
        cid = get_id(s["company_name"])
        if cid:
            conn.execute(
                """INSERT INTO leadership_signals (company_id, leader_name, leader_title,
                   signal_type, content, source_url, date_observed, impact_level)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                (cid, s["leader_name"], s["leader_title"], s["signal_type"],
                 s["content"], s["source_url"], s["date_observed"], s["impact_level"]),
            )
            counts["leadership"] += 1

    for s in SEED_AI_SIGNALS:
        cid = get_id(s["company_name"])
        if cid:
            conn.execute(
                """INSERT INTO ai_signals (company_id, signal_type, title, source_url,
                   source_name, excerpt, signal_strength, date_observed)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                (cid, s["signal_type"], s["title"], s.get("source_url"),
                 s.get("source_name"), s.get("excerpt"), s["signal_strength"],
                 s["date_observed"]),
            )
            counts["signals"] += 1

    for t in SEED_TOOLS:
        cid = get_id(t["company_name"])
        if cid:
            conn.execute(
                """INSERT INTO tools_adopted (company_id, tool_name, adoption_level,
                   evidence_url, date_observed)
                   VALUES (?, ?, ?, ?, ?)""",
                (cid, t["tool_name"], t["adoption_level"],
                 t.get("evidence_url"), t.get("date_observed")),
            )
            counts["tools"] += 1

    conn.commit()

    refresh_all_scores(conn)

    return counts
